### PR TITLE
Document how to allow install hooks for mutable packages in AEM Cloud

### LINKED ISSUE #31: Add option to allow mutable install hooks for local AEM SDK development
When developing with the AEM SDK, a common approach is to use InstallHook's to trigger actions when a mutable content package is installed. This is for example done by the Netcentric accesscontroltool. To make it possible to leverage this capability, there should be an option to disable the error for install hooks in mutable content for local development

### PR DESCRIPTION
**Pull request by kwin**
This closes #31

### CODE REVIEW

**Comment by kwin** [comment]
@royteeuwen Please have a look

**Comment by royteeuwen** [comment]
Super 👌🏼

**Comment by royteeuwen** [comment]
@kwin  you think you can cut in a release for this :) ?

**Comment by kwin** [comment]
Release is done @royteeuwen

**Pull request merged**
